# POS Tags
# from http://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html
#
# CC	Coordinating conjunction
# CD	Cardinal number
# DT	Determiner
# EX	Existential there
# FW	Foreign word
# IN	Preposition or subordinating conjunction
# JJ	Adjective
# JJR	Adjective, comparative
# JJS	Adjective, superlative
# LS	List item marker
# MD	Modal
# NN	Noun, singular or mass
# NNS	Noun, plural
# NNP	Proper noun, singular
# NNPS	Proper noun, plural
# PDT	Predeterminer
# POS	Possessive ending
# PRP	Personal pronoun
# PRP$	Possessive pronoun
# RB	Adverb
# RBR	Adverb, comparative
# RBS	Adverb, superlative
# RP	Particle
# SYM	Symbol
# TO	to
# UH	Interjection
# VB	Verb, base form
# VBD	Verb, past tense
# VBG	Verb, gerund or present participle
# VBN	Verb, past participle
# VBP	Verb, non-3rd person singular present
# VBZ	Verb, 3rd person singular present
# WDT	Wh-determiner
# WP	Wh-pronoun
# WP$	Possessive wh-pronoun
# WRB	Wh-adverb

# Source dictionary generated by identify_pos.py
from source_pos_repeat import source

pattern = ['MD']
f = open('../matching_pos/' + str(pattern) + 'pos_repeat' + '.txt', 'w+')

def matching_pos():
    keys_seen = set()
    with f:
        f.write('\n' + str(pattern) + '\n\n')
        while True:
            for pos in pattern:
                for k, v in source.items():
                    if pos == v and k.lower().rstrip() not in keys_seen:
                        f.write(k + ' ')
                        keys_seen.add(k.lower().rstrip())
                        break
                else:
                    return
                f.write('\n')

matching_pos()
